// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzabrbdqmzbidbzwcbtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YWJyYmRxbXpiaWRiendjYnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODExOTcsImV4cCI6MjA2NjI1NzE5N30.w9Qno-QKxPqgackh3bA8XL49zJXZf525otBbZNzaDzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);